# Generated by Django 2.1.3 on 2019-05-19 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='senha_cliente',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
