# Generated by Django 2.1.3 on 2019-05-19 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCliente', '0002_cliente_senha_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='usuario_cliente',
        ),
    ]
