# Generated by Django 2.1.3 on 2019-05-07 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appCliente', '0002_auto_20190507_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='senha_cliente',
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.OneToOneField(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='Cliente', to=settings.AUTH_USER_MODEL),
        ),
    ]
