# Generated by Django 2.1.3 on 2019-05-07 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCliente', '0003_auto_20190507_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='usuario',
            new_name='usuario_cliente',
        ),
    ]
