# Generated by Django 2.1.3 on 2019-05-12 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_prop', models.CharField(max_length=255)),
                ('email_prop', models.EmailField(max_length=254)),
                ('nome_loc_prop', models.CharField(blank=True, max_length=250, null=True)),
                ('usuario_prop', models.OneToOneField(default='', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Propietario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_vaga', models.IntegerField()),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appProprietario.Proprietario')),
            ],
        ),
    ]
