# Generated by Django 2.1.3 on 2019-05-08 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_prop', models.CharField(max_length=255)),
                ('email_prop', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_vaga', models.IntegerField()),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appProprietario.Proprietario')),
            ],
        ),
    ]
