# Generated by Django 2.1.3 on 2019-05-08 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProprietario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprietario',
            name='senha_prop',
            field=models.CharField(default='', max_length=30),
        ),
    ]
