# Generated by Django 2.1.3 on 2019-05-09 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appProprietario', '0002_proprietario_senha_prop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proprietario',
            name='senha_prop',
        ),
        migrations.AddField(
            model_name='proprietario',
            name='usuario_prop',
            field=models.OneToOneField(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='Propietario', to=settings.AUTH_USER_MODEL),
        ),
    ]
