# Generated by Django 2.1.3 on 2019-10-12 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appProprietario', '0002_auto_20191008_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaga',
            name='cliente_vaga',
        ),
    ]
