# Generated by Django 2.1.3 on 2019-05-09 23:06

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appProprietario', '0003_auto_20190509_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprietario',
            name='position',
            field=geoposition.fields.GeopositionField(default='', max_length=42),
        ),
    ]
