# Generated by Django 2.1.3 on 2019-05-10 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail', '__first__'),
        ('appProprietario', '0004_proprietario_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proprietario',
            name='id',
        ),
        migrations.RemoveField(
            model_name='proprietario',
            name='position',
        ),
        migrations.AddField(
            model_name='proprietario',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='proprietario',
            name='page_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtail.Page'),
            preserve_default=False,
        ),
    ]
