# Generated by Django 2.1.3 on 2019-10-14 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appProprietario', '0004_vaga_ocupada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente_Vaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.OneToOneField(default='', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Cliente', to='appProprietario.Cliente')),
                ('vaga', models.OneToOneField(default='', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Vaga', to='appProprietario.Vaga')),
            ],
        ),
    ]
