# Generated by Django 2.1.3 on 2019-05-10 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appProprietario', '0005_auto_20190509_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proprietario',
            options={'ordering': ('usuario_prop',), 'verbose_name': 'Sua Classe', 'verbose_name_plural': 'Suas Classes'},
        ),
        migrations.RenameField(
            model_name='proprietario',
            old_name='location',
            new_name='nome_loc_prop',
        ),
        migrations.AddField(
            model_name='proprietario',
            name='position',
            field=geoposition.fields.GeopositionField(default='', help_text='Não altere os valores calculados automaticamente de latitude e longitude', max_length=42, verbose_name='Geolocalização'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='usuario_prop',
            field=models.OneToOneField(default='', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Propietario', to=settings.AUTH_USER_MODEL),
        ),
    ]
