# Generated by Django 2.1.3 on 2019-10-18 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appProprietario', '0008_cliente_is_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprietario',
            name='is_prop',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='usuario_cli',
            field=models.OneToOneField(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='Cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='usuario_prop',
            field=models.OneToOneField(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='prop', to=settings.AUTH_USER_MODEL),
        ),
    ]
