# Generated by Django 2.1.3 on 2019-10-19 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appProprietario', '0009_auto_20191018_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proprietario',
            name='nome_loc_prop',
        ),
    ]
