# Generated by Django 2.1.3 on 2019-10-28 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appProprietario', '0013_auto_20191023_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='prop',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prop_vaga', to='appProprietario.Proprietario'),
        ),
    ]
