# Generated by Django 3.0.2 on 2020-02-21 00:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProprietario', '0014_auto_20191028_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente_vaga',
            name='hora_entrada',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='cliente_vaga',
            name='hora_saida',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cliente_vaga',
            name='total_transacao',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cliente_vaga',
            name='transacao_is_terminada',
            field=models.BooleanField(default=False),
        ),
    ]
