# Generated by Django 3.0.2 on 2020-03-12 20:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appProprietario', '0020_auto_20200311_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente_vaga',
            name='hora_entrada',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 12, 20, 0, 44, 831812, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='tipo_vaga',
            field=models.CharField(choices=[('n', 'Normal'), ('i', 'Idoso'), ('g', 'Gestante'), ('d', 'Deficiente')], max_length=255),
        ),
    ]
