# Generated by Django 3.0.2 on 2020-04-16 13:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appProprietario', '0021_auto_20200312_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente_vaga',
            name='transacao_em_andamento',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cliente_vaga',
            name='hora_entrada',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 16, 13, 50, 23, 945433, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='tipo_vaga',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Idoso', 'Idoso'), ('Gestante', 'Gestante'), ('Deficiente', 'Deficiente')], max_length=255),
        ),
    ]
