# Generated by Django 3.0.5 on 2020-05-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProprietario', '0022_auto_20200416_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente_vaga',
            name='hora_entrada',
            field=models.DateTimeField(blank=True),
        ),
    ]
