# Generated by Django 3.0.5 on 2020-05-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProprietario', '0023_auto_20200511_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente_vaga',
            name='hora_entrada',
            field=models.DateTimeField(null=True),
        ),
    ]
