# Generated by Django 3.0.5 on 2020-07-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProprietario', '0024_auto_20200511_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprietario',
            name='valor_prop',
            field=models.IntegerField(default=0.1),
        ),
    ]
